version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      #- MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=tpfoyerdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-tpfoyer:
    depends_on:
      - mysqldb
    image: henirebhi_5sleam1
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/tpfoyerdb?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
