version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app-foyer:
    image: tp-foyer-app
    container_name: app-foyer
    depends_on:
      - mysqldb
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring": {
          "datasource": {
            "url": "jdbc:mysql://mysqldb:3306/foyer_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
            "username": "root",
            "password": "root"
          },
          "jpa": {
            "properties": {
              "hibernate": {
                "dialect": "org.hibernate.dialect.MySQLDialect"
              }
            },
            "hibernate": {
              "ddl-auto": "update"
            }
          }
        },
        "management": {
          "endpoints": {
            "web": {
              "exposure": {
                "include": "*"
              },
              "base-path": "/actuator"
            },
            "health": {
              "show-details": "always"
            },
            "prometheus": {
              "enabled": true
            },
            "metrics": {
              "enabled": true
            }
          }
        },
        "logging": {
          "level": {
            "org.springframework.boot.actuate": "DEBUG"
          }
        }
      }'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  db_data:
