version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app-foyer:
    image: tp-foyer-app
    container_name: app-foyer
    depends_on:
      - mysqldb
    ports:
      - "8089:8089"

  mysqld-exporter:
    image: prom/mysqld-exporter:main
    container_name: mysqld-exporter
    volumes:
      - ./config.my-cnf:/cfg/config.my-cnf # Ensure this path is correct
    command:
      - --config.my-cnf=/cfg/config.my-cnf
    environment:
      DATA_SOURCE_NAME: "root:root@(mysqldb:3306)/foyer_db" # Connect to MySQL service
    ports:
      - "9104:9104"

volumes:
  db_data:
