version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app-foyer:
    image: tp-foyer-app1
    container_name: app-foyer1
    depends_on:
      - mysqldb
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/foyer_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    depends_on:
      - mysqldb  # Correct the service name here from `mysql` to `mysqldb`
    command:
      - --config.my-cnf=/cfg/.my.cnf  # Correct the file path here
      - --mysqld.address=localhost:3306
    volumes:
      - ./my.cnf:/cfg/.my.cnf  # Correct the path to your `.my.cnf` file
    ports:
      - "9104:9104"

volumes:
  db_data:
