global:
  scrape_interval: 15s  # How often to scrape targets by default.

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-foyer:8089']  # Use the service name and port of your Spring Boot app.