version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    depends_on:
      - mysql
    command:
      - --config.my-cnf=/cfg/..my.cnf
      - --mysqld.address=localhost:3306
    volumes:
      - ./ ..my.cnf:/cfg/..my.cnf
    ports:
      - "9104:9104"

volumes:
  db_data:
